name = "garbage-duty-assigner"
main = "src/worker.ts"
compatibility_date = "2026-03-15"
compatibility_flags = ["nodejs_compat"]

[vars]
APP_TIMEZONE = "America/Halifax"
SCHEDULE_SOURCE = "halifax"

[[d1_databases]]
binding = "DB"
database_name = "garbage-duty-assigner"
database_id = "1c99f586-ecbc-4938-9be6-5795b595bc86"

[triggers]
crons = ["5 * * * *"]
